name: build64

on: workflow_dispatch

jobs:
  GenerateWinStaticBinaries:
    runs-on: windows-2022

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Install Python 3.12 version
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      if: contains(matrix.os, 'windows')
    - uses: seanmiddleditch/gha-setup-ninja@v5
    - name: Clone Qt repo
      run: |
        git clone https://code.qt.io/qt/qt5.git qt -b 6.8.3
        cd qt
        perl init-repository.pl -f --module-subset=qt5compat,qt3d,qtbase,qtcharts,qtdeclarative,qtimageformats,qtlanguageserver,qtmqtt,qtmultimedia,qtnetworkauth,qtquick3d,qtquicktimeline,qtserialbus,qtserialport,qtshadertools,qtsvg,qtwebchannel,qtwebengine,qtwebsockets,qtwebview

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      if: contains(matrix.os, 'windows')

    - name: Build Qt (Windows)
      if: contains(matrix.os, 'windows')
      env:
        CL: /MP # Build with multiple processes
      run: |
        mkdir qt_build
        cd qt_build
        ..\qt\configure.bat -release -static -static-runtime -no-pch -optimize-size win32-msvc -prefix "..\Qt6_binaries" -no-feature-accessibility -confirm-license
        cmake --build . --parallel 4
        cmake --install .
    - name: Package binaries
      run: |
        # Create archive of the pre-built Qt binaries
        7z a qt6_683_static_64.zip ..\Qt6_binaries
    - uses: actions/upload-artifact@v4
      with:
        name: qt6_683_static_64
        path: qt6_683_static_64.zip
